import type { AnalysisResponse } from "./types";

/**
 * Generate formatted Markdown from analysis response
 */
export function generateMarkdown(analysis: AnalysisResponse): string {
  const lines: string[] = [];

  // Header
  lines.push("# Resume Analysis Report");
  lines.push("");
  lines.push(`**Overall Score:** ${analysis.overall_score}/100`);
  lines.push(`**Verdict:** ${formatVerdict(analysis.overall_verdict)}`);
  lines.push("");

  // Roast Summary
  lines.push("## The Roast 🔥");
  lines.push("");
  lines.push(analysis.roast_summary);
  lines.push("");

  // Quick Wins
  if (analysis.quick_wins.length > 0) {
    lines.push("## Quick Wins ⚡");
    lines.push("");
    analysis.quick_wins.forEach((qw) => {
      const priorityEmoji =
        qw.priority === "high" ? "🔴" : qw.priority === "medium" ? "🟡" : "🟢";
      lines.push(`- ${priorityEmoji} **${qw.priority.toUpperCase()}:** ${qw.text}`);
    });
    lines.push("");
  }

  // ATS Keywords
  if (analysis.ats_analysis.keywords_missing.length > 0) {
    lines.push("## Missing ATS Keywords ⚠️");
    lines.push("");
    lines.push(`**ATS Score:** ${analysis.ats_analysis.score}/100`);
    lines.push("");
    lines.push("**Keywords to add:**");
    lines.push(analysis.ats_analysis.keywords_missing.map((k) => `\`${k}\``).join(", "));
    lines.push("");
  }

  // Sections
  lines.push("## Section Analysis");
  lines.push("");

  analysis.sections.forEach((section) => {
    const severityEmoji =
      section.severity === "critical"
        ? "🔴"
        : section.severity === "warning"
          ? "🟡"
          : "🟢";

    lines.push(`### ${section.name} ${severityEmoji}`);
    lines.push("");
    lines.push(`**Score:** ${section.score}/100 (${formatSeverity(section.severity)})`);
    lines.push("");

    // Original
    lines.push("#### Original");
    lines.push("");
    lines.push("```");
    lines.push(section.original);
    lines.push("```");
    lines.push("");

    // Improved
    lines.push("#### Improved ✨");
    lines.push("");
    lines.push("```");
    lines.push(section.improved);
    lines.push("```");
    lines.push("");

    // Improvement Notes
    if (section.improvement_notes) {
      lines.push("#### Why These Changes?");
      lines.push("");
      lines.push(section.improvement_notes);
      lines.push("");
    }

    lines.push("---");
    lines.push("");
  });

  // Footer
  lines.push("*Generated by Resume Roaster AI*");

  return lines.join("\n");
}

/**
 * Format verdict for display
 */
function formatVerdict(verdict: string): string {
  switch (verdict) {
    case "brutal_honesty_needed":
      return "Brutal Honesty Needed";
    case "needs_work":
      return "Needs Work";
    case "solid_foundation":
      return "Solid Foundation";
    case "exceptional":
      return "Exceptional";
    default:
      return verdict;
  }
}

/**
 * Format severity for display
 */
function formatSeverity(severity: string): string {
  switch (severity) {
    case "critical":
      return "Critical";
    case "warning":
      return "Needs Improvement";
    case "good":
      return "Good";
    default:
      return severity;
  }
}

/**
 * Download markdown as file
 */
export function downloadMarkdown(analysis: AnalysisResponse, filename?: string): void {
  const markdown = generateMarkdown(analysis);
  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = filename || `resume-analysis-${Date.now()}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}
